AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener with Lambda, API Gateway, and DynamoDB

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Environment:
      Variables:
        TABLE_NAME: ShortenedURLsTable

  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:

  ## DynamoDB Table
  ShortenedURLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShortenedURLsTable
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ## Lambda: ShortenURL
  ShortenURLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/shortenURL.handler
      CodeUri: .
      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ShortenedURLsTable

  ## Lambda: Redirect
  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/redirect.handler
      CodeUri: .
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /redirect/{shortCode}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: ShortenedURLsTable

Outputs:
  ShortenAPI:
    Description: "POST URL for shortening"
    Value: 
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorten"

  RedirectAPI:
    Description: "GET URL for redirecting"
    Value: 
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/redirect/{shortCode}"
